Scrum 5 create model form
mentorbridgeindia/stublab pull request #15
Opened 2024-12-19 15:06 UTC by Umarfarook1912

Api Integration code modified

2024-12-20 18:14 UTC, mentorbridgeindia requested changes

2024-12-27 08:42 UTC, Umarfarook1912 commented on src/pages/Model/CreatePage/CreateModelPage.tsx
> -      const response = await sendData("http://localhost:8080/add", jsonData);
If i didn't use axios, it didn't work properly sir

2024-12-27 08:43 UTC, Umarfarook1912 reviewed
I use axios instead of sendData because it doesnot work properly

2024-12-27 10:25 UTC, mentorbridgeindia approved these changes

2024-12-27 10:30 UTC, merged