Scrum 5 create model form
mentorbridgeindia/stublab pull request #8
Opened 2024-12-11 14:47 UTC by Umarfarook1912

## JIRA User story link

### Things I had implemented in my task

_________________

#### PR Checklist
- [x] Develop a UI design for Model API form.
- [x] Implement hooks form for easy validation.
- [x] Display error message with help of formstate.
- [x] ToastContainer for display toast message.

2024-12-11 15:21 UTC, mentorbridgeindia requested changes

2024-12-11 15:21 UTC, mentorbridgeindia commented on src/pages/model-form/model-form/ModelForm.css
Rename folder name to caps ModelForm and dont create multiple subfolders with same name modle-form/model-form

2024-12-11 15:21 UTC, mentorbridgeindia commented on src/pages/model-form/model-form/ModelForm.css
> +    width: 1230px;
Dont set width explicitly

2024-12-11 15:21 UTC, mentorbridgeindia commented on src/pages/model-form/model-form/ModelForm.css
> +    display: flex;
try using **d-flex justify-content-between align-start** in className

2024-12-11 15:21 UTC, mentorbridgeindia commented on src/pages/model-form/model-form/ModelForm.css
> +    gap: 30px;
use gap-4

2024-12-11 15:21 UTC, mentorbridgeindia commented on src/pages/model-form/model-form/ModelForm.css
> +    display: flex;
same use **d-flex** classname

2024-12-11 15:21 UTC, mentorbridgeindia commented on src/App.tsx
> +import 'bootstrap/dist/css/bootstrap.min.css';
import this in App.css, not here

2024-12-11 15:21 UTC, mentorbridgeindia commented on src/pages/model-form/model-form/ModelForm.css
> +    width: 86px;
Don't set width explicitly

2024-12-11 15:21 UTC, mentorbridgeindia commented on src/pages/model-form/model-form/ModelForm.css
> +    height: 45px;
Don't set height explicitly

2024-12-11 15:21 UTC, mentorbridgeindia commented on src/pages/model-form/model-form/ModelForm.css
> +     font-family: 'Times New Roman', Times, serif;
Font name changed for a particular element? why?

2024-12-11 15:21 UTC, mentorbridgeindia commented on src/pages/model-form/model-form/ModelForm.css
> +    font-family: 'Times New Roman', Times, serif;
Again font family changed

2024-12-11 15:21 UTC, mentorbridgeindia commented on src/pages/model-form/model-form/ModelForm.tsx
> +    console.log("Generated JSON:", jsonData);
Remove console logs before committing

2024-12-11 15:21 UTC, mentorbridgeindia commented on src/pages/model-form/model-form/ModelForm.tsx
> +          {/* Model Name Input */}
Remove unwanted commented lines

2024-12-11 15:21 UTC, mentorbridgeindia commented on src/pages/model-form/model-form/ModelForm.tsx
> +          {/* Variables Section */}
remove comment

2024-12-13 05:48 UTC, mentorbridgeindia approved these changes

2024-12-13 05:48 UTC, mentorbridgeindia commented
Resolve conflicts before you merge

2024-12-13 05:48 UTC, mentorbridgeindia requested changes
Resolve merge conflicts

2024-12-13 05:49 UTC, mentorbridgeindia commented
Take latest pull from main and resolve conflicts

2024-12-13 06:08 UTC, Umarfarook1912 commented
I solve the conflicts and merge my branch sir thank you .Please proceed further

2024-12-13 06:10 UTC, Umarfarook1912 reviewed
completed

2024-12-14 07:17 UTC, closed without merging